hm:
  db:
    database: hm-user
    port: 3306
    un: root
    pw: root
    host: 192.168.174.128 # 修改为你自己的虚拟机IP地址
  swagger:
    title: user-service
    packages-to-scan: com.jiangkai.userservice.controller